version: "3.7"

services:

  rtmp_nginx:
    build: ./services/rtmp_nginx
    ports:
      - 1935:1935
    env_file: .env
    networks:
      - server_network

  # api:
  #   build: ./services/api
  #   restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 5000:5000
  #   environment:
  #     # Environment is from .env file
  #     - AUTH_TOKEN
  #   networks:
  #     - server_network

  # mongo:
  #   image: mongo:3.4.23-xenial
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - mongo:/data/db
  #   networks:
  #     - server_network

  # audio_streaming_icecast:
  #   build: ./services/audio_streaming/icecast
  #   ports:
  #     - "8000:8000"
  #   environment:
  #     - "ICECAST_HOSTNAME=audio_streaming_icecast"
  #     - "ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}"
  #     - "ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}"
  #     - "ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD}"
  #     - "ICECAST_ADMIN_USERNAME=${ICECAST_ADMIN_USERNAME}"
  #     # - "ICECAST_ADMIN_EMAIL=${ICECAST_ADMIN_EMAIL}"
  #     # - "ICECAST_LOCATION=${ICECAST_LOCATION}"
  #     # - "ICECAST_MAX_CLIENTS=${ICECAST_MAX_CLIENTS}"
  #     # - "ICECAST_MAX_SOURCES=${ICECAST_MAX_SOURCES}"
  #   restart: always
  #   networks:
  #     - server_network

# volumes:
#   mongo:

networks:
  server_network:
