version: "3.7"

services:

  nginx:
    image: linuxserver/letsencrypt
    depends_on:
      - rtmp_nginx
    # container_name: nginx
    cap_add:
      - NET_ADMIN
    environment:
      - PUID="${PUID}"
      - PGID="${PGID}"
      - TZ="${TZ}"
      - URL="${URL}"
      - SUBDOMAINS="${SUBDOMAINS}"
      - VALIDATION=http
      # - DNSPLUGIN=cloudflare #optional
      # - DUCKDNSTOKEN=token #optional
      # - EMAIL=e-mail #optional
      # - DHLEVEL=2048 #optional
      - ONLY_SUBDOMAINS=true #optional
      # - EXTRA_DOMAINS=extradomains #optional
      - STAGING=false #optional
    volumes:
      - ./config/nginx/config:/config
      # Customise the nginx config with an overridden version
      - ./config/nginx/custom/site-confs/default:/config/nginx/site-confs/default
    ports:
      - 443:443
      - 80:80
      - 1935:1935
    networks:
      - server_network
