psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER metabase;
	ALTER USER metabase WITH PASSWORD '$MB_DB_PASS';
	CREATE DATABASE metabase;
	GRANT ALL PRIVILEGES ON DATABASE metabase TO metabase;
EOSQL
