# Generated by Django 3.0.7 on 2020-06-27 22:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organisation name', max_length=1024)),
                ('logo', models.ImageField(blank=True, help_text='Image of the logo of the sponsor', null=True, upload_to='logos')),
                ('sponsorship_level', models.CharField(blank=True, choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], help_text='Sponsorship level of the sponsor', max_length=10, null=True)),
            ],
        ),
    ]
