# Generated by Django 3.0.7 on 2020-06-27 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organisation", "0001_initial"),
        ("hive", "0003_auto_20200621_0025"),
    ]

    operations = [
        migrations.RemoveField(model_name="hive", name="logo",),
        migrations.AddField(
            model_name="hive",
            name="sponsor",
            field=models.ForeignKey(
                blank=True,
                help_text="Sponsoring organisation of this hive",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="organisation.Organisation",
            ),
        ),
    ]
