# Generated by Django 3.0.7 on 2020-07-04 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0005_auto_20200628_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='url_name',
            field=models.CharField(default='graf', help_text="Short name used for the hive's URL", max_length=1024, unique=True),
            preserve_default=False,
        ),
    ]
