version: "3.7"

services:

  api:
    build: ./services/api
    restart: always
    depends_on:
      - mongo
    ports:
      - 5000:5000
    environment:
      # Environment is from .env file
      - AUTH_TOKEN
    networks:
      - server_network

  mongo:
    image: mongo:3.4.23-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - server_network

volumes:
  mongo:

networks:
  server_network:
