version: "3.7"
services:
  app:
    build: .
    restart: always
    ports:
      - 5000:5000
    environment:
      # Environment is from .env file
      - AUTH_TOKEN
  mongo:
    image: mongo:3.4.23-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo

volumes:
  mongo:
