version: "3.8"

services:

  # Nginx with Let's Encrypt as the front facing and SSL terminating reverse proxy
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    cap_add:
      - NET_ADMIN
    env_file: .env
    volumes:
      - nginx_config:/config
      - ./nginx/nginx.conf:/config/nginx/nginx.conf
      - ./nginx/default:/config/nginx/site-confs/default
      - static:/static
      - media:/media
    ports:
      - "443:443"
      - "80:80"
      - "1935:1935"
    restart: unless-stopped
    networks:
      - server_network

volumes:
  nginx_config:
