version: "3.7"

services:

  api:
    build: ./services/api
    restart: always
    depends_on:
      - mongo
    ports:
      - 5000:5000
    environment:
      # Environment is from .env file
      - AUTH_TOKEN
    networks:
      - server_network
      - mongo_network

  mongo:
    image: mongo:3.4.23-xenial
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db
    networks:
      - server_network
      - mongo_network

  metabase:
    image: metabase/metabase
    depends_on: 
      - postgres
    ports:
      - 3000:3000
    networks:
      - server_network
    environment:
      # Environment is from .env file
      - AUTH_TOKEN
      - "MB_DB_TYPE=postgres"
      - "MB_DB_DBNAME=metabase"
      - "MB_DB_PORT=5432"
      - "MB_DB_USER=metabase"
      - "MB_DB_PASS={$MB_DB_PASS}"
      - "MB_DB_HOST=postgres"
    networks:
      - server_network
      - mongo_network
      - postgres_network

  postgres:
    image: postgres:12.0
    restart: always
    volumes:
      - ./services/postgres/init:/docker-entrypoint-initdb.d:ro
    # environment: 
    #   - "POSTGRES_PASSWORD=F83E34A6-E259-4A53-8B9A-6E795076F774"
    networks:
      - postgres_network

  audio_streaming_icecast:
    build: ./services/audio_streaming/icecast
    ports:
      - "8000:8000"
    environment:
      - "ICECAST_HOSTNAME=audio_streaming_icecast"
      - "ICECAST_SOURCE_PASSWORD=${ICECAST_SOURCE_PASSWORD}"
      - "ICECAST_ADMIN_PASSWORD=${ICECAST_ADMIN_PASSWORD}"
      - "ICECAST_RELAY_PASSWORD=${ICECAST_RELAY_PASSWORD}"
      - "ICECAST_ADMIN_USERNAME=${ICECAST_ADMIN_USERNAME}"
      # - "ICECAST_ADMIN_EMAIL=${ICECAST_ADMIN_EMAIL}"
      # - "ICECAST_LOCATION=${ICECAST_LOCATION}"
      # - "ICECAST_MAX_CLIENTS=${ICECAST_MAX_CLIENTS}"
      # - "ICECAST_MAX_SOURCES=${ICECAST_MAX_SOURCES}"
    restart: always
    networks:
      - server_network

volumes:
  mongo:

networks:
  server_network:
  mongo_network:
  postgres_network:
