version: "3.8"

services:

  # Apiary Django app
  apiary:
    volumes:
        # Mount the code in during development
        - ./backend/apiary:/app
    ports:
      # Expose Django app in development only
      - "8000:8000"
