version: "3.8"

services:
  # RTMP stream receiving nginx
  nginx_rtmp:
    build:
      context: ./nginx_rtmp
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - type: tmpfs
        target: /hlstmp
    networks:
      - server_network

  # Apiary Django app
  apiary:
    build:
      context: ./backend/apiary
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./apps/apiary:/app
      - static:/static
      - media:/media
    depends_on:
      - postgres
    restart: always
    networks:
      - server_network
      - db_network

  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
    restart: always
    networks:
      - db_network

volumes:
  postgres:
  static:
  media:

networks:
  server_network:
  db_network:
