version: "3.8"

services:
  # RTMP stream receiving nginx
  nginx_rtmp:
    build:
      context: ./nginx_rtmp
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - type: tmpfs
        target: /hlstmp
    networks:
      - server_network

  # Apiary Django app
  apiary:
    build:
      context: ./backend/apiary
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - postgres
    restart: always
    networks:
      - server_network
      - db_network

  # Postgres backing the Django app
  postgres:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD
    restart: always
    networks:
      - db_network

  # ThingsBoard IOT sensor database and dashboards
  thingsboard:
    restart: always
    image: thingsboard/tb-postgres:3.2.2
    volumes:
      - thingsboard_data:/data
      - thingsboard_logs:/var/log/thingsboard
    expose:
      - "9090"
    restart: always
    networks:
      - server_network
      - thingsboard_network
    depends_on:
      - rabbitmq
    env_file:
      - .env

  # RabbitMQ message broker for ThingsBoard
  rabbitmq:
    restart: always
    build:
      context: ./rabbitmq
      dockerfile: rabbitmq.Dockerfile
    expose:
      - "5672"
    networks:
      - thingsboard_network
    env_file:
      - .env
    ports:
      - "8081:15672"


volumes:
  postgres:
  static:
  media:
  thingsboard_data:
  thingsboard_logs:

networks:
  server_network:
  db_network:
  thingsboard_network:
