version: "3.8"

services:

  # Apiary Django app
  apiary:
    volumes:
        # Mount the code in during development
        - ./backend/apiary:/app
    ports:
      # Expose Django app in development only
      - "8000:8000"

  thingsboard:
    ports:
      - "8080:9090"
      - "1883:1883"
      - "5683:5683/udp"
    environment:
      TB_QUEUE_TYPE: in-memory

  rabbitmq:
    ports:
      - "8081:15672""
