# Generated by Django 3.0.7 on 2020-07-11 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='url',
            field=models.CharField(blank=True, help_text='URL of the organisation', max_length=2048, null=True),
        ),
    ]
