# Generated by Django 3.2.4 on 2021-08-01 18:14

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0003_auto_20200809_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Image of the logo of the organisation', keep_meta=False, null=True, quality=100, size=[120, 120], upload_to='logos'),
        ),
    ]
