# Generated by Django 3.0.7 on 2020-08-09 13:46

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_organisation_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='logo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='PNG', help_text='Image of the logo of the organisation', keep_meta=False, null=True, quality=90, size=[40, 40], upload_to='logos'),
        ),
    ]
