hives:
  hosts:
    currenthostname:
      # Hostname to set this Pi to
      pi_hostname: desiredhostname
      # Password for the pi user
      pi_password: thepassword
  vars:
    ansible_user: pi
