# Generated by Django 3.0.7 on 2020-06-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='logo',
            field=models.ImageField(blank=True, help_text='Image of the logo of the sponsor of this hive', null=True, upload_to='avatars'),
        ),
    ]
