# Generated by Django 3.2.4 on 2021-08-01 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0007_auto_20200721_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hive',
            name='uid',
            field=models.CharField(help_text='Unique hive ID', max_length=1024, unique=True),
        ),
    ]
