# Generated by Django 3.2.4 on 2021-08-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0008_alter_hive_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='hive',
            name='dashboard_active',
            field=models.BooleanField(default=True, help_text="Determines if this hive's dashboard should be accessible publicly through the apiary interface"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hive',
            name='dashboard_id',
            field=models.UUIDField(blank=True, help_text='ID of the Thingsboard dashboard for this hive (if it exists)', null=True),
        ),
        migrations.AddField(
            model_name='hive',
            name='dashboard_public_id',
            field=models.UUIDField(blank=True, help_text='Public ID of the Thingsboard dashboard for this hive (if it exists)', null=True),
        ),
    ]
