# Generated by Django 3.2.4 on 2021-08-08 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hive', '0009_auto_20210801_1820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hive',
            name='dashboard_id',
        ),
        migrations.RemoveField(
            model_name='hive',
            name='dashboard_public_id',
        ),
        migrations.AddField(
            model_name='hive',
            name='dashboard_url',
            field=models.URLField(blank=True, help_text='URL of the Grafana dashboard template to display sensor data for this hive', null=True),
        ),
    ]
