version: "3.7"

services:

  # environment:
    # build: ./services/environment
    # restart: always
    # environment:
      # Environment is from .env file
      # - AUTH_TOKEN
      # - SERVER
      # - HIVE_ID
    # Required for GPIO access
    # privileged: true

  # audio_sampling:
  #   build: ./services/audio_sampling
  #   restart: always
  #   environment:
  #     # Environment is from .env file
  #     - AUTH_TOKEN

  # audio_streaming_darkice:
  #   build: ./services/audio_streaming/darkice
  #   privileged: true
  #   restart: always
  #   networks:
  #     - streaming_network

  # audio_streaming_liquidsoap:
    # build: ./services/audio_streaming/liquidsoap
    # privileged: true
    # restart: always
    # networks:
      # - streaming_network

  av_streaming_picam:
    build: ./services/av_streaming/picam
    privileged: true
    restart: always
    env_file: .env
    volumes:
      - type: tmpfs
        target: /shm
    networks:
      - streaming_network
    # ports:
    #   - 8181:8181

  # av_streaming_picam_test_nginx:
  #   image: tiangolo/nginx-rtmp
  #   restart: always
  #   env_file: .env
  #   networks:
  #     - streaming_network
  #   ports:
  #     - 1935:1935

  # av_streaming_ffmpeg:
  #   build: ./services/av_streaming/ffmpeg
  #   privileged: true
  #   restart: always
  #   env_file: .env
  #   networks:
  #     - streaming_network

networks:
  streaming_network: