version: "3.7"

services:

  environment:
    build: ./services/environment
    restart: always
    environment:
      # Environment is from .env file
      - AUTH_TOKEN
    # Required for GPIO access
    devices:
      - "/dev/gpiomem:/dev/gpiomem"

  # audio:
  #   build: ./services/audio
  #   restart: always
  #   environment:
  #     # Environment is from .env file
  #     - AUTH_TOKEN
