version: "3.7"

services:

  # environment:
    # build: ./services/environment
    # restart: always
    # environment:
      # Environment is from .env file
      # - AUTH_TOKEN
      # - SERVER
      # - HIVE_ID
    # Required for GPIO access
    # privileged: true

  av_streaming_picam:
    # depends_on:
    #   - av_streaming_ffmpeg
    build: ./services/av_streaming/picam
    privileged: true
    restart: always
    env_file: .env
    volumes:
      - type: tmpfs
        target: /shm
    networks:
      - streaming_network
    healthcheck:
      # Check if ffmpeg is running: if not, kill the container
      test: "ps aux | grep ffmpeg | grep --invert-match grep || killall picam"
      interval: 15s
      timeout: 5s
      retries: 1

networks:
  streaming_network:
