version: "3.7"

services:

  # environment:
    # build: ./services/environment
    # restart: always
    # environment:
      # Environment is from .env file
      # - AUTH_TOKEN
      # - SERVER
      # - HIVE_ID
    # Required for GPIO access
    # privileged: true

  av_streaming_picam:
    # depends_on:
    #   - av_streaming_ffmpeg
    build: ./services/av_streaming/picam
    privileged: true
    restart: always
    env_file: .env
    volumes:
      - type: tmpfs
        target: /shm
    networks:
      - streaming_network
    healthcheck:
      # Check if ffmpeg is running: if not, kill the container
      test: ["CMD", "ps aux | grep ffmpeg | grep --invert-match grep"]
      interval: 10s
      timeout: 5s
      retries: 1

  # av_streaming_ffmpeg:
  #   build: ./services/av_streaming/ffmpeg
  #   restart: always
  #   env_file: .env
  #   networks:
  #     - streaming_network
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "$STREAM_HEALTHCHECK_URL"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 2

networks:
  streaming_network:
