version: "3.7"

services:

  environment:
    build: ./services/environment
    restart: always
    environment:
      # Environment is from .env file
      - AUTH_TOKEN
      - SERVER
      - HIVE_ID
    # Required for GPIO access
    privileged: true

  # audio:
  #   build: ./services/audio
  #   restart: always
  #   environment:
  #     # Environment is from .env file
  #     - AUTH_TOKEN
