---
- name: Configure Raspberry Pis for hive usage
  import_playbook: pi_configuration.yml
- name: Set up Docker on Raspberry Pis
  import_playbook: docker_setup.yml
- name: Checkout the latest bee_iot codebase
  import_playbook: repo_setup.yml

# TODO:
# - Microphone setup
# - Set up envs for compose
# - Run compose
