---
- name: remote.it setup
  hosts: hives
  remote_user: pi

  tasks:

  # Prevent remote.it connectd from being upgraded
  # https://support.remote.it/hc/en-us/articles/360051668711
  - name: Prevent connectd from being upgraded
    become: true
    dpkg_selections:
      name: connectd
      selection: hold

  # Install connectd
  - name: Install connectd
    when: remoteit_enabled
    become: true
    ansible.builtin.apt:
      update_cache: true
      name: connectd
      state: present
    register: connectd_install

  # Copy over the registration script
  - name: Copy over the registration script
    when: remoteit_enabled and connectd_install.changed
    ansible.builtin.template:
      src: connectd_register.j2
      dest: /tmp/connectd_register.sh
      mode: 0600
    register: registration_script

  # Register this Pi with remote.it
  - name: Register this Pi with remote.it
    when: remoteit_enabled and registration_script.changed
    become: true
    ansible.builtin.command: sh /tmp/connectd_register.sh

  # Ensure the registration script containing credentials is removed
  - name: Remove the registration script
    ansible.builtin.file:
      path: /tmp/connectd_register.sh
      state: absent
