---
- name: Run the hive software
  hosts: hives
  remote_user: pi

  tasks:

  - name: Set up .env file for the hive
    ansible.builtin.template:
      src: hive_env.j2
      dest: /home/pi/bee_iot/hive/.env
      mode: 0644

  # Run compose. Force recreate if env has changed
  - name: Run hive software
    # when: env_file.changed
    community.docker.docker_compose:
      project_src: /home/pi/bee_iot/hive
      state: present
      pull: true
      build: true
      remove_orphans: true
      recreate: smart
